name: Django Tests with Docker Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug workspace (نمایش درخت فایل‌ها)
      run: |
        echo "Current folder:"
        pwd
        echo "List content:"
        ls -R .

    - name: Build containers
      run: |
        docker compose -f ../../docker-compose.yml build

    - name: Start DB and Redis
      run: |
        docker compose -f ../../docker-compose.yml up -d db redis
        echo "⏳ Waiting for Postgres..."
        until docker exec db pg_isready -U postgres; do sleep 1; done

    - name: Run migrations
      run: |
        docker compose -f ../../docker-compose.yml run --rm backend sh -c "python manage.py migrate --noinput"

    - name: Run tests
      run: |
        docker compose -f ../../docker-compose.yml run --rm backend pytest -vv

    - name: Stop Docker Compose
      if: always()
      run: |
        docker compose -f ../../docker-compose.yml down
